### ISSUE TITLE
Orderer v3: update fabric-proto-go dependency 

### ISSUE THREAD

**Issue by tock-ibm** [hyperledger/fabric-config#54]
config protobuf messages changed with the new BFT work. The dependency below needs to be updated to reflect fabric main:
`github.com/hyperledger/fabric-protos-go v0.0.0-20200424173316-dd554ba3746e`

->

`github.com/hyperledger/fabric-protos-go v0.3.0`

also update to go 1.20

**Comment by MayRosenbaum** [comment]
I'll take it

**Comment by denyeart** [comment]
Thanks @MayRosenbaum 

Actually we'd like to move to `github.com/hyperledger/fabric-protos-go-apiv2 v0.3.0` since fabric-admin-sdk uses fabric-protos-go-apiv2 and intends to pull in fabric-config dependency.

@SamYuan1990 is it ok for fabric-admin-sdk to go to v0.3.0 as well? Hopefully that doesn't cause any problem supporting both Fabric v2.5 (protos v0.2.0) and Fabric v3.0 (protos v0.3.0).

**Comment by tock-ibm** [comment]
@MayRosenbaum  After some discussions, the path forward is to:

- First move fabric-config to `github.com/hyperledger/fabric-protos-go v0.3.0`, in order to pick up the related BFT changes for v3. 
- Later, as part of a bigger move to upgrade fabric to `github.com/hyperledger/fabric-protos-go-apiv2 v0.3.0`, to change fabric-config to that implementation (see https://github.com/hyperledger/fabric/issues/3650).

In this issue we'll handle the first part, #53 will be used for the second part.
